import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.scss";

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'

// Components
import Footer from './components/Footer'

const poppins = Poppins({ subsets: ["latin"], variable: '--font-poppins', display: "swap", weight: ['300', '400', '500', '600', '700', '800'] });
config.autoAddCss = false

export const metadata: Metadata = {
  title: "Artifical Labs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
